#!/bin/sh

#create swap
if [ -e /var/etc/.swapcreate.sh ]; then
	/usr/bin/showiframe /boot/bootlogo_swap.mvi
	/var/etc/.swapcreate.sh
	rm -f /var/etc/.swapcreate.sh
	/usr/bin/showiframe /boot/bootlogo.mvi
fi

[ -e /usr/script/mount.sh ] && /usr/script/mount.sh
[ -e /usr/bin/nemesisd ] && /usr/bin/nemesisd &

#Start tihrd-part at boot
list=`ls /var/etc/*_startup.sh`
for item in $list
	do
		${item} start
	done

#Activate Swap
[ -e /media/usb/swapfile ] && swapon /media/usb/swapfile
[ -e /media/cf/swapfile ] && swapon /media/cf/swapfile
[ -e /media/hdd/swapfile ] && swapon /media/hdd/swapfile

#Restore EPG
[ -e /media/cf/epg.dat.save ] && cp /media/cf/epg.dat.save /media/cf/epg.dat
[ -e /media/hdd/epg.dat.save ] && cp /media/hdd/epg.dat.save /media/hdd/epg.dat
[ -e /media/usb/epg.dat.save ] && cp /media/usb/epg.dat.save /media/usb/epg.dat
