#!/bin/sh
DAEMON=/usr/bin/inadyn
NAME=inadyn
DESC='InaDyn dynamic DNS Client'
name='InaDyn'
binary='inadyn'

if [ -e /etc/inadyn.conf ]; then
	test -f $DAEMON || exit 0
	case "$1" in
	start)
		$DAEMON
		;;
	stop)
		killall -9 $NAME
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
	esac
fi

exit 0
